{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:36:22Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5257",
  "summary": "Malicious code in imagesolverpy (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "imagesolverpy",
        "purl": "pkg:pypi/imagesolverpy"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "fd1084294d4bf79a3b40949bf714084fa5398d23bb068d694eaedfdd2920931f",
        "import_time": "2024-06-28T02:49:13.383483659Z",
        "id": "RLMA-2024-04039",
        "modified_time": "2024-06-25T13:36:22Z",
        "versions": [
          "1.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "f41b647042986dbd25f66e00f2e50e437f71702d876c6bf344c663d0ffe5e33d",
        "import_time": "2024-10-24T00:59:20.043904604Z",
        "id": "RLUA-2024-08399",
        "modified_time": "2024-10-16T14:42:29Z"
      }
    ]
  }
}
