{
  "modified": "2024-10-24T01:01:57Z",
  "published": "2024-06-25T13:32:45Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4809",
  "aliases": [
    "SNYK-PYTHON-BIPUTILES-6513405"
  ],
  "summary": "Malicious code in bip-utiles (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "bip-utiles",
        "purl": "pkg:pypi/bip-utiles"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIPUTILES-6513405"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "f70af98a65b43df03e0e4b67d4290770e81699cce0eb949108e85675b3cc5845",
        "import_time": "2024-06-28T02:48:20.78731826Z",
        "id": "RLMA-2024-03589",
        "modified_time": "2024-06-25T13:32:45Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "c50bd2f0d62864a14bb880356a8f8d75d9517ac50ea720444c6877598276740e",
        "import_time": "2024-10-24T00:58:49.522280034Z",
        "id": "RLUA-2024-07868",
        "modified_time": "2024-10-16T14:36:52Z"
      }
    ]
  }
}
