{
  "modified": "2025-03-03T13:44:38Z",
  "published": "2025-03-03T13:44:38Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-1963",
  "summary": "Malicious code in astronomio (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "astronomio",
        "purl": "pkg:pypi/astronomio"
      },
      "versions": [
        "0.5"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-01198",
        "import_time": "2025-03-03T15:07:13.821117764Z",
        "modified_time": "2025-03-03T13:44:38Z",
        "sha256": "2554b538538908997b6615b6c25c5662287f2f4198397eed2ef00fda6e7447d6",
        "source": "reversing-labs",
        "versions": [
          "0.5"
        ]
      }
    ]
  }
}
