{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:35:38Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5166",
  "aliases": [
    "SNYK-PYTHON-FSHEC2-5672158"
  ],
  "summary": "Malicious code in fshec2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "fshec2",
        "purl": "pkg:pypi/fshec2"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-FSHEC2-5672158"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.reversinglabs.com/blog/when-python-bytecode-bites-back-who-checks-the-contents-of-compiled-python-files"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "d195cc25d02e51e3b6471b3880ab9b23dd2599eaa6bf4d95bac0a27d1d830d90",
        "import_time": "2024-06-28T02:49:02.22536154Z",
        "id": "RLMA-2024-03948",
        "modified_time": "2024-06-25T13:35:38Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "c00279325343d0ba7ff4bf3f6fc01ddd987b9b87146a0ea06c8df3b03a94fe29",
        "import_time": "2024-10-24T00:59:14.185690795Z",
        "id": "RLUA-2024-08304",
        "modified_time": "2024-10-16T14:41:29Z"
      }
    ]
  }
}
