{
  "modified": "2025-01-08T09:31:18Z",
  "published": "2025-01-08T09:31:18Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-36",
  "summary": "Malicious code in rtpoc1 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (167f71321a3854879568e4d1e2caaebc490967f77f2f1a949123ce5c6ceae8fe)\nThe OpenSSF Package Analysis project identified 'rtpoc1' @ 0.2 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "rtpoc1"
      },
      "versions": [
        "0.2"
      ]
    }
  ],
  "credits": [
    {
      "name": "OpenSSF: Package Analysis",
      "type": "FINDER",
      "contact": [
        "https://github.com/ossf/package-analysis",
        "https://openssf.slack.com/channels/package_analysis"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "import_time": "2025-01-08T09:34:44.887400868Z",
        "modified_time": "2025-01-08T09:31:18Z",
        "sha256": "167f71321a3854879568e4d1e2caaebc490967f77f2f1a949123ce5c6ceae8fe",
        "source": "ossf-package-analysis",
        "versions": [
          "0.2"
        ]
      }
    ]
  }
}
