{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:41:31Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5876",
  "aliases": [
    "SNYK-PYTHON-REQUEKSTS-6513384"
  ],
  "summary": "Malicious code in requeksts (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requeksts",
        "purl": "pkg:pypi/requeksts"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUEKSTS-6513384"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "4615022a80d6e09a7b9bd2777b09d94feedd6eb70b06cce8909510b6d90c88eb",
        "import_time": "2024-06-28T02:50:28.650717815Z",
        "id": "RLMA-2024-04677",
        "modified_time": "2024-06-25T13:41:31Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "616d902e8ff926b359397285b57efa84e35e8fc8f7ce58acd9d38a6be5ef31f5",
        "import_time": "2024-10-24T01:00:02.446788216Z",
        "id": "RLUA-2024-09136",
        "modified_time": "2024-10-16T14:50:02Z"
      }
    ]
  }
}
