{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:38:08Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5476",
  "summary": "Malicious code in pillov (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pillov",
        "purl": "pkg:pypi/pillov"
      },
      "versions": [
        "10.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "ac6826cc26f3b71bd244992eae8cf48f0cafcef462b3b0d4f27c67bead7b4cac",
        "import_time": "2024-06-28T02:49:38.869098681Z",
        "id": "RLMA-2024-04258",
        "modified_time": "2024-06-25T13:38:08Z",
        "versions": [
          "10.0.1"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "e07c6b37809f05a6a2bdfa43649ebf6c814c2ce3daf87f095dab8f505997b2e5",
        "import_time": "2024-10-24T00:59:35.260688457Z",
        "id": "RLUA-2024-08686",
        "modified_time": "2024-10-16T14:45:26Z"
      }
    ]
  }
}
