{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:43:16Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-6097",
  "summary": "Malicious code in tasksaio (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "tasksaio",
        "purl": "pkg:pypi/tasksaio"
      },
      "versions": [
        "0.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "aa7d7929acda0cae21c666967d6b11d7006ba408542c960d62e50d67244591d7",
        "import_time": "2024-06-28T02:50:55.903418217Z",
        "id": "RLMA-2024-04900",
        "modified_time": "2024-06-25T13:43:16Z",
        "versions": [
          "0.0.1"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "b00d2dc0fff0e2bee21bce459f907a70683b7ff233cf75eda1f93da01fab7cf0",
        "import_time": "2024-10-24T01:00:17.629238138Z",
        "id": "RLUA-2024-09368",
        "modified_time": "2024-10-16T14:52:24Z"
      }
    ]
  }
}
