{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:38:45Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5553",
  "summary": "Malicious code in plutodebug (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "plutodebug",
        "purl": "pkg:pypi/plutodebug"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "2071b3942e42aced97905dbe44452f6d8689b482a8ab72b8b0f69b0dbd2890d9",
        "import_time": "2024-06-28T02:49:48.189839597Z",
        "id": "RLMA-2024-04335",
        "modified_time": "2024-06-25T13:38:45Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "1a3e35741525e5c30d9a8bca9fc4226117e88b6ddacef2af8620f976d63be865",
        "import_time": "2024-10-24T00:59:40.127215425Z",
        "id": "RLUA-2024-08763",
        "modified_time": "2024-10-16T14:46:13Z"
      }
    ]
  }
}
