{
  "modified": "2024-10-16T14:53:41Z",
  "published": "2024-10-16T14:53:41Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-10196",
  "summary": "Malicious code in wdb3 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "wdb3",
        "purl": "pkg:pypi/wdb3"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-09495",
        "import_time": "2024-10-24T00:57:11.41678203Z",
        "modified_time": "2024-10-16T14:53:41Z",
        "sha256": "b4e1abfbd22c6f55f274036a357b78e73d884fa22e3c354a77cab038d6679ff1",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
