{
  "modified": "2025-07-31T19:14:35Z",
  "published": "2025-07-31T19:14:35Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-6480",
  "summary": "Malicious code in cloudx-base (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "cloudx-base",
        "purl": "pkg:pypi/cloudx-base"
      },
      "versions": [
        "0.1.12",
        "1.2.0",
        "1.2.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-03565",
        "import_time": "2025-08-01T10:07:10.437014313Z",
        "modified_time": "2025-07-31T19:14:35Z",
        "sha256": "4bb2f7047ec34a36a64dcf7a0963fc13979e8685c6d0c4b492a6c767042f12f7",
        "source": "reversing-labs",
        "versions": [
          "0.1.12",
          "1.2.0",
          "1.2.1"
        ]
      }
    ]
  }
}
