{
  "modified": "2023-05-20T14:00:35Z",
  "published": "2023-05-20T14:00:35Z",
  "schema_version": "1.5.0",
  "id": "MAL-2023-1395",
  "summary": "Malicious code in pylint-sys (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (b069b475056c2219d8f5f62b9e0479ba4dfb9a18639f9afd674c9ef90359882d)\nThe OpenSSF Package Analysis project identified 'pylint-sys' @ 8.15.6 (pypi) as malicious.\n\nIt is considered malicious because:\n- The package communicates with a domain associated with malicious activity.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pylint-sys"
      },
      "versions": [
        "8.15.6"
      ]
    }
  ],
  "credits": [
    {
      "name": "OpenSSF: Package Analysis",
      "type": "FINDER",
      "contact": [
        "https://github.com/ossf/package-analysis",
        "https://openssf.slack.com/channels/package_analysis"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "import_time": "2023-08-10T06:17:05.114899526Z",
        "modified_time": "2023-05-20T14:00:35.082410288Z",
        "sha256": "b069b475056c2219d8f5f62b9e0479ba4dfb9a18639f9afd674c9ef90359882d",
        "source": "ossf-package-analysis",
        "versions": [
          "8.15.6"
        ]
      }
    ]
  }
}
